// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using Microsoft.ML;
using Microsoft.ML.Data;

namespace MLBuild
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"col0")]
            public float Col00 { get; set; }

            [ColumnName(@"col1")]
            public float Col01 { get; set; }

            [ColumnName(@"col2")]
            public float Col02 { get; set; }

            [ColumnName(@"col3")]
            public float Col03 { get; set; }

            [ColumnName(@"col4")]
            public float Col04 { get; set; }

            [ColumnName(@"col5")]
            public float Col05 { get; set; }

            [ColumnName(@"col6")]
            public float Col06 { get; set; }

            [ColumnName(@"col7")]
            public float Col07 { get; set; }

            [ColumnName(@"col8")]
            public float Col08 { get; set; }

            [ColumnName(@"col9")]
            public float Col09 { get; set; }

            [ColumnName(@"col10")]
            public float Col10 { get; set; }

            [ColumnName(@"col11")]
            public float Col11 { get; set; }

            [ColumnName(@"col12")]
            public float Col12 { get; set; }

            [ColumnName(@"col13")]
            public float Col13 { get; set; }

            [ColumnName(@"col14")]
            public float Col14 { get; set; }

            [ColumnName(@"col15")]
            public float Col15 { get; set; }

            [ColumnName(@"col16")]
            public float Col16 { get; set; }

            [ColumnName(@"col17")]
            public float Col17 { get; set; }

            [ColumnName(@"col18")]
            public float Col18 { get; set; }

            [ColumnName(@"col19")]
            public float Col19 { get; set; }

            [ColumnName(@"col20")]
            public float Col20 { get; set; }

            [ColumnName(@"col21")]
            public float Col21 { get; set; }

            [ColumnName(@"col22")]
            public float Col22 { get; set; }

            [ColumnName(@"col23")]
            public float Col23 { get; set; }

            [ColumnName(@"col24")]
            public float Col24 { get; set; }

            [ColumnName(@"col25")]
            public float Col25 { get; set; }

            [ColumnName(@"col26")]
            public float Col26 { get; set; }

            [ColumnName(@"col27")]
            public float Col27 { get; set; }

            [ColumnName(@"col28")]
            public float Col28 { get; set; }

            [ColumnName(@"col29")]
            public float Col29 { get; set; }

            [ColumnName(@"col30")]
            public float Col30 { get; set; }

            [ColumnName(@"col31")]
            public float Col31 { get; set; }

            [ColumnName(@"col32")]
            public float Col32 { get; set; }

            [ColumnName(@"col33")]
            public float Col33 { get; set; }

            [ColumnName(@"col34")]
            public float Col34 { get; set; }

            [ColumnName(@"col35")]
            public float Col35 { get; set; }

            [ColumnName(@"col36")]
            public float Col36 { get; set; }

            [ColumnName(@"col37")]
            public float Col37 { get; set; }

            [ColumnName(@"col38")]
            public float Col38 { get; set; }

            [ColumnName(@"col39")]
            public float Col39 { get; set; }

            [ColumnName(@"col40")]
            public float Col40 { get; set; }

            [ColumnName(@"col41")]
            public float Col41 { get; set; }

            [ColumnName(@"col42")]
            public float Col42 { get; set; }

            [ColumnName(@"col43")]
            public float Col43 { get; set; }

            [ColumnName(@"col44")]
            public float Col44 { get; set; }

            [ColumnName(@"col45")]
            public float Col45 { get; set; }

            [ColumnName(@"col46")]
            public float Col46 { get; set; }

            [ColumnName(@"col47")]
            public float Col47 { get; set; }

            [ColumnName(@"col48")]
            public float Col48 { get; set; }

            [ColumnName(@"col49")]
            public float Col49 { get; set; }

            [ColumnName(@"col50")]
            public float Col50 { get; set; }

            [ColumnName(@"col51")]
            public float Col51 { get; set; }

            [ColumnName(@"col52")]
            public float Col52 { get; set; }

            [ColumnName(@"col53")]
            public float Col53 { get; set; }

            [ColumnName(@"col54")]
            public float Col54 { get; set; }

            [ColumnName(@"col55")]
            public float Col55 { get; set; }

            [ColumnName(@"col56")]
            public float Col56 { get; set; }

            [ColumnName(@"col57")]
            public float Col57 { get; set; }

            [ColumnName(@"col58")]
            public float Col58 { get; set; }

            [ColumnName(@"col59")]
            public float Col59 { get; set; }

            [ColumnName(@"col60")]
            public float Col60 { get; set; }

            [ColumnName(@"col61")]
            public float Col61 { get; set; }

            [ColumnName(@"col62")]
            public float Col62 { get; set; }

            [ColumnName(@"col63")]
            public float Col63 { get; set; }

            [ColumnName(@"col64")]
            public float Col64 { get; set; }

            [ColumnName(@"col65")]
            public float Col65 { get; set; }

            [ColumnName(@"col66")]
            public float Col66 { get; set; }

            [ColumnName(@"col67")]
            public float Col67 { get; set; }

            [ColumnName(@"col68")]
            public float Col68 { get; set; }

            [ColumnName(@"col69")]
            public float Col69 { get; set; }

            [ColumnName(@"col70")]
            public float Col70 { get; set; }

            [ColumnName(@"col71")]
            public float Col71 { get; set; }

            [ColumnName(@"col72")]
            public float Col72 { get; set; }

            [ColumnName(@"col73")]
            public float Col73 { get; set; }

            [ColumnName(@"col74")]
            public float Col74 { get; set; }

            [ColumnName(@"col75")]
            public float Col75 { get; set; }

            [ColumnName(@"col76")]
            public float Col76 { get; set; }

            [ColumnName(@"col77")]
            public float Col77 { get; set; }

            [ColumnName(@"col78")]
            public float Col78 { get; set; }

            [ColumnName(@"col79")]
            public float Col79 { get; set; }

            [ColumnName(@"col80")]
            public float Col80 { get; set; }

            [ColumnName(@"col81")]
            public float Col81 { get; set; }

            [ColumnName(@"col82")]
            public float Col82 { get; set; }

            [ColumnName(@"col83")]
            public float Col83 { get; set; }

            [ColumnName(@"col84")]
            public float Col84 { get; set; }

            [ColumnName(@"col85")]
            public float Col85 { get; set; }

            [ColumnName(@"col86")]
            public float Col86 { get; set; }

            [ColumnName(@"col87")]
            public float Col87 { get; set; }

            [ColumnName(@"col88")]
            public float Col88 { get; set; }

            [ColumnName(@"col89")]
            public float Col89 { get; set; }

            [ColumnName(@"col90")]
            public float Col90 { get; set; }

            [ColumnName(@"col91")]
            public float Col91 { get; set; }

            [ColumnName(@"col92")]
            public float Col92 { get; set; }

            [ColumnName(@"col93")]
            public float Col93 { get; set; }

            [ColumnName(@"col94")]
            public float Col94 { get; set; }

            [ColumnName(@"col95")]
            public float Col95 { get; set; }

            [ColumnName(@"col96")]
            public float Col96 { get; set; }

            [ColumnName(@"col97")]
            public float Col97 { get; set; }

            [ColumnName(@"col98")]
            public float Col98 { get; set; }

            [ColumnName(@"col99")]
            public float Col99 { get; set; }

            [ColumnName(@"col100")]
            public float Col100 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
